In [3]:
import numpy as np

In [2]:
#numpy创建并查看数组属性
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print('形状',arr1.shape)
print('维度',arr1.ndim)
print('元素类型',arr1.dtype)
print('元素个数',arr1.size)
print('储存空间',arr1.itemsize)

[[1 2 3 4]
 [5 6 7 8]]
形状 (2, 4)
维度 2
元素类型 int32
元素个数 8
储存空间 4


In [3]:
#重设数组形状
arr1.shape=4,2
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#arange函数
#arange(start,stop,step,dtype)
arr2=np.arange(0,1,0.1,dtype=np.float64)
arr2.dtype

dtype('float64')

In [5]:
#linspace函数,等间隔生成数字
#np.linspace(start,stop,num,endpoint=True,dtype),endpoint代表是否包含终止值,默认包含
arr3=np.linspace(0,5,50,dtype=np.float64)
arr3

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [6]:
#logspace函数,生成等比数列数组
#np.logspace(start,stop,num,endpoint=True,dtype)
arr4=np.logspace(0,2,10)
arr4

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [7]:
#zeros函数,生成全0数组
arr5=np.zeros((2,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#eye函数,生成类似单位矩阵的数组
arr6=np.eye(2)
arr6

array([[1., 0.],
       [0., 1.]])

In [9]:
#diag函数,生成对角线元素任意,其余位置为零的数组
arr7=np.diag([1,2,0,4])
arr7

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 4]])

In [10]:
#ones函数,生成全为一的数组
arr8=np.ones((4,8))
arr8

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
#数据类型转换
a=np.float64(1)
b=np.int8(2.0)
c=np.bool_(3)
d=np.bool_(0)
print(a,b,c,d)

1.0 2 True False


In [12]:
#随机数的生成
#random生成无规律随机数
ar1=np.random.random(5)#5个
print(ar1)
#rand生成服从均匀分布的随机数
ar2=np.random.rand(2,4)#2行4列
print(ar2)
#randn生成服从正态分布的随机数
ar3=np.random.randn(2,2)
print(ar3)

[0.17446048 0.07179186 0.80764048 0.19743837 0.97824899]
[[0.40361208 0.9384713  0.60787062 0.89686218]
 [0.3241136  0.90270214 0.66401302 0.5790209 ]]
[[ 0.1244698   1.72513733]
 [-0.68078681  0.31239493]]


In [13]:
#randint函数,生成给定范围的随机数
#np.random.randint(low,high=None,size=None,dtype=None)
arr9=np.random.randint(4,10,size=[4,5])
arr9

array([[6, 7, 5, 8, 5],
       [9, 9, 4, 7, 6],
       [4, 8, 4, 7, 8],
       [4, 6, 5, 8, 9]])

In [40]:
#数组索引
#一维数组索引
arrex_1=np.arange(10)
print(arrex_1)
print(arrex_1[5])#提取某个元素
#索引切片
print(arrex_1[3:5])#包括3不包括5
print(arrex_1[:5])#从省略开始索引,不包括5
print(arrex_1[-3])#从后往前第三个元素

[0 1 2 3 4 5 6 7 8 9]
5
[3 4]
[0 1 2 3 4]
7


In [48]:
#索引可用于修改元素的值
arrex_1[2:4]=100,70
print(arrex_1)
#第三个参数代表步长,代表隔几个元素取一个,步长为负时,开始索引要大于结束索引
print(arrex_1[5:1:-2])

[  0   1 100  70   4   5   6   7   8   9]
[ 5 70]


In [30]:
#多维数组索引
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)
print(arr[0,3:5])#索引第0行中3,4列的元素
print(arr[1:,2:])#索引第1-2行中2-4列的元素
print(arr[:,2])#索引第二列的元素
print(arr[2])#索引第二行的元素
print(arr[[0,1,2],[1,2,3]])#索引(0,1),(1,2),(2,3)位置的元素
print(arr[1:,(0,2,3)])#索引1-2行中0,2,3位置的元素

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[4 5]
[[ 8  9 10]
 [13 14 15]]
[ 3  8 13]
[11 12 13 14 15]
[ 2  8 14]
[[ 6  8  9]
 [11 13 14]]


In [44]:
#布尔数组索引
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
mask=np.array([1,0,1],dtype=bool)#选择第0行和第2行,第1行跳过
print(arr[mask,2])#从选取的行中选择索引为2的列

[ 3 13]


In [60]:
#改变数组的形状
arr=np.arange(12)
print(arr.reshape(2,6))#.reshape(),改变数组的长和宽和维度
print(arr.reshape(2,6).ravel())#.ravel()展平数组
print(arr.reshape(2,6).flatten('F'))#.flatten()横向展平,.flatten('F')纵向展平

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  6  1  7  2  8  3  9  4 10  5 11]


In [76]:
#组合与分割
arr1=np.arange(12).reshape(3,4)
arr2=arr1**2
print(arr1,'\n',arr2)
#横向组合:np.hstack(),np.concatenate((),axis=1)
print(np.hstack((arr1,arr2)))
print(np.concatenate((arr1,arr2),axis=1))
#纵向组合:np.vstack(),np.concatenate((),axis=0)
print(np.vstack((arr1,arr2)))
print(np.concatenate((arr1,arr2),axis=0))
#横向分割:

#纵向分割:


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[  0   1   2   3   0   1   4   9]
 [  4   5   6   7  16  25  36  49]
 [  8   9  10  11  64  81 100 121]]
[[  0   1   2   3   0   1   4   9]
 [  4   5   6   7  16  25  36  49]
 [  8   9  10  11  64  81 100 121]]
[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
